wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.33
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.7.10
    t:
      3:
      - 2
      4: 3.7.10
      5: 0.10.33
      8:
      - 1
      - 2
      - 5
    visualize:
      Atypical Appearance:
        panel_config:
          fieldSettings:
            label: Atypical Appearance
            value: counts
          panelDefId: wandb/bar/v0
          stringSettings:
            title: Atypical Appearance
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: Atypical Appearance_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
_wandb_kernel:
  desc: null
  value: saifmu6
competition:
  desc: null
  value: siim-fisabio-rsna-covid-19-detection
