wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.33
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.7.10
    t:
      4: 3.7.10
      5: 0.10.33
      8:
      - 1
      - 2
      - 5
